def register(rt):
    rt.register("node://{target}/query/health", "python://urisysnode.handlers:query_health", kind="query", operation="node.health")
    rt.register("node://{target}/query/identity", "python://urisysnode.handlers:query_identity", kind="query", operation="node.identity")
    rt.register(
        "node://{target}/command/indicator-on",
        "python://urisysnode.handlers:command_indicator_on",
        kind="command",
        operation="node.indicator_on",
        approval="required",
        side_effects=True,
    )
    rt.register(
        "node://{target}/command/indicator-off",
        "python://urisysnode.handlers:command_indicator_off",
        kind="command",
        operation="node.indicator_off",
        approval="required",
        side_effects=True,
    )
    rt.register(
        "node://{target}/query/packs",
        "python://urisysnode.handlers:query_packs",
        kind="query",
        operation="node.packs",
    )
    rt.register(
        "node://{target}/command/install-pack",
        "python://urisysnode.handlers:command_install_pack",
        kind="command",
        operation="node.install_pack",
        approval="required",
        side_effects=True,
    )
    rt.register(
        "node://{target}/command/register-forward",
        "python://urisysnode.handlers:command_register_forward",
        kind="command",
        operation="node.register_forward",
        approval="required",
        side_effects=True,
    )
    rt.register(
        "node://{target}/query/workers",
        "python://urisysnode.handlers:query_workers",
        kind="query",
        operation="node.workers",
    )
    rt.register(
        "node://{target}/command/spawn-worker",
        "python://urisysnode.handlers:command_spawn_worker",
        kind="command",
        operation="node.spawn_worker",
        approval="required",
        side_effects=True,
    )
    rt.register(
        "node://{target}/command/restart-worker",
        "python://urisysnode.handlers:command_restart_worker",
        kind="command",
        operation="node.restart_worker",
        approval="required",
        side_effects=True,
    )
    rt.register(
        "node://{target}/command/stop-worker",
        "python://urisysnode.handlers:command_stop_worker",
        kind="command",
        operation="node.stop_worker",
        approval="required",
        side_effects=True,
    )
