def register(rt):
    rt.register(
        "screen://{target}/monitor/{monitor}/query/frame",
        "python://uriscreen.handlers:frame",
        kind="query",
        operation="screen.frame",
    )
    rt.register(
        "screen://{target}/monitor/{monitor}/command/capture",
        "python://uriscreen.handlers:capture",
        kind="command",
        operation="screen.capture",
        approval="required",
        side_effects=True,
    )
    rt.register(
        "screen://{target}/capture/command/loop",
        "python://uriscreen.handlers:capture_loop",
        kind="command",
        operation="screen.capture_loop",
        approval="required",
        side_effects=True,
    )
